### ISSUE TITLE
Regression: Trying to Screenshare anything other than an output crashes

### ISSUE THREAD

**Issue by Luk45135** [pop-os/xdg-desktop-portal-cosmic#110]
Expected:
working screenshare like before

What actually happens:
when doing any of the following the portal window closes and freezes (in this instance vesktop) and then crashes the application (vesktop)
1. trying to select the tab Windows in the portal window
2. closing the portal window

Just Screensharing an output e.g. a display works without issues

this appeared somewhere between
xdg-desktop-portal-cosmic-1.0.0-alpha.3-unstable-2024-10-10
and
xdg-desktop-portal-cosmic-1.0.0-alpha.3-unstable-2024-11-15

I'm using NixOS 25.05.20241115.5e4fbfb (Warbler)

**Comment by Quackdoc** [comment]
I believe this to be related to the issue I bisected, can you try commits `7c83138` and `b1ad418`  to verify?

**Comment by Luk45135** [comment]
@Quackdoc idk how to, im not that good at packaging on nix and figuring out all the correct dependencies seems like a pain. i can try revert before this commit https://github.com/lilyinstarlight/nixos-cosmic/commit/c294772655f83716e69f5585cb8b3aec049998a6 which includes b1ad418 but also a bunch of other commits

**Comment by gilvbp** [comment]
I'm trying  to Screenshare using Teams PWA (Wayland), which closes when I start sharing.

LOG: `ERROR xdg_desktop_portal_cosmic::screencast_thread] screencopy failed: Value(BufferConstraints)`

**Comment by Luk45135** [comment]
Okay, so half of this is fixed. Streaming windows works now but closing the portal window still crashes vesktop, but now i'm not sure anymore if this is a portal issue or a vesktop/discord issue.

**Comment by amozeo** [comment]
> closing the portal window still crashes vesktop
this was happening to vesktop since alpha 1

**Comment by Luk45135** [comment]
@amozeo should i close/rename this issue?

**Comment by amozeo** [comment]
> should i close/rename this issue?

If you think this issue no longer applies then close it
