### ISSUE TITLE
Basic screenshare python script results in green screen

### ISSUE THREAD

**Issue by Quackdoc** [pop-os/xdg-desktop-portal-cosmic#39]
Not really sure what is going on here. I currently uses a modified version of this script to handle various screencasting stuff. https://gitlab.gnome.org/-/snippets/19

However when this script is run it results in a green screen. as far as I know gstreamer should be able to handle format stuff. I have used this before in gnome without issues.

EDIT: this seems to only happen with xvimagesink, so I guess it's more likely to be a xwayland issue? Closing and moving to cosmic-comp

**Comment by Drakulix** [comment]
Any specific reason, why you need the `xvimagesink` instead e.g. the `ximagesink` or `waylandsink`. I am not sure how well the Xvideo extension works with Xwayland.

**Comment by Quackdoc** [comment]
No other reason then that is what the script defaulted to, so no major one anyways and waylandsink will work fine for me. waylandsink and glimagesink can be a bit buggy at times, but it's reliable enough for my usecase. also for anyone coming across this you may need to use `... ! videoconvert ! video/x-raw ! waylandsink` or you may not need to
