### ISSUE TITLE
OBS PipeWire capture no longer works

### ISSUE THREAD

**Issue by ryanabx** [pop-os/xdg-desktop-portal-cosmic#46]
PipeWire capture no longer shows any available displays to capture

![screenshot-2024-05-25-17-22-47](https://github.com/pop-os/xdg-desktop-portal-cosmic/assets/56272643/e60ab5fa-bad3-4db7-a7ec-dd86e2c2e942)

Likely the offending commit: https://github.com/pop-os/xdg-desktop-portal-cosmic/commit/ddafa7b4506673abb8b219d1f8016ea87b3badb8#diff-8cd8df4f536f3b7978164bd2953e645b6f45b81e6fb552ffb3616e3cca74478b

cc: @wash2

**Comment by plushrib** [comment]
```
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=cosmic 

systemctl --user stop pipewire wireplumber xdg-desktop-portal xdg-desktop-portal-wlr

```

 temporarily solves it
