### ISSUE TITLE
ravif v0.11.7 cannot be built because it requires rustc 1.79 or newer

### ISSUE THREAD

**Issue by joostruis** [pop-os/xdg-desktop-portal-cosmic#55]
Not sure if you are aware of this, reporting it anyway.

INFO cargo build --release --frozen --bin xdg-desktop-portal-cosmic
INFO error: package `ravif v0.11.7` cannot be built because it requires rustc 1.79 or newer, while the currently active rustc version is 1.77.1
Either upgrade to rustc 1.79 or newer, or use
cargo update ravif@0.11.7 --precise ver
where `ver` is the latest version of `ravif` supporting rustc 1.77.1

**Comment by mmstick** [comment]
You must update to Rust 1.79.0

**Comment by joostruis** [comment]
Yes, no problem, just wanted to make sure you are aware of this build requirement. It seems everything else compiles fine using 1.77.1 (currently the stable version on Gentoo)

**Comment by mmstick** [comment]
Yes, we have updated to 1.79.0 in Pop!_OS
