### ISSUE TITLE
Screencasting in Firefox or Discord shows black screen.

### ISSUE THREAD

**Issue by maggster165** [pop-os/xdg-desktop-portal-cosmic#93]
Running Fedora 40 with the latest packages from COPR, although it happens in the PopOS alpha iso as well.
Logs show this error:
`ERROR xdg_desktop_portal_cosmic::screencast_thread] screencopy failed: Value(BufferConstraints)`

**Comment by jbdamiano** [comment]
same issue with slack screen sharing
the sharing  is working only when I share a  window or the laptop internal display
When I try to share my external display the windows is black

The feature is working with gnome

I am on POP OS 24.04 and update with staging/master

journalctl error log with issue

    Sep 20 20:46:22 pop-os cosmic-session[25263]: [2024-09-20T18:46:22Z ERROR xdg_desktop_portal_cosmic::screencast_thread] screencopy failed: Value(BufferConstraints)
    Sep 20 20:46:22 pop-os /usr/libexec/gdm-wayland-session[25263]: 2024-09-20T18:46:22.521950Z WARN xdg-desktop-portal-cosmic: cosmic_session: [2024-09-20T18:46:22Z ERROR xdg_desktop_portal_cosmic::screencast_thread] screencopy failed: Value(BufferConstraints)

**Comment by WatchMkr** [comment]
Also reported with Zoom Workplace

**Comment by authenticastrology** [comment]
> Also reported with Zoom Workplace

Ditto. I was told that they are aiming to fix for Alpha 3.

**Comment by vadorovsky** [comment]
The next xdg-desktop-portal-cosmic release should fix it. As a workaround, you can edit `/usr/share/xdg-desktop-portal/portals/cosmic.portal` and replace the last line:

```
UseIn=cosmic
```

to:

```
UseIn=COSMIC
```

The upper-case value there should fix the issue and made screencasting working for me.

**Comment by authenticastrology** [comment]
I have still not been able to screenshare and although it used to work from the browser, now browser functionality is also broken.

**Comment by GosuTeacher** [comment]
Fedora Workstation 41
DM: cosmic-greeter
xdg-desktop-portal-cosmic.x86_64  1.0.0~alpha.3^git20241204.e7c92a7-1.fc41
GPU: AMD

```
cosmic-session[2671]: [2024-12-07T14:22:16Z ERROR xdg_desktop_portal_cosmic::screencast_thread] screencopy failed: Value(BufferConstraints)
```

**Comment by ximnoise** [comment]
The problem still exists in Alpha 4 on Arch Linux with Firefox. 
I can not screenshare in multiple web applications (Galene, Mattermost, etc.).

@jackpot51 @vadorovsky can you please reopen this issue?
